### ISSUE TITLE
Can the author provide a grey Orange theme

### ISSUE THREAD

**Issue by jahnli** [rexebin/darkpurple#2] opened 2020-10-15 02:54 UTC
Can the author provide a grey Orange theme
[grey_orange.zip](https://github.com/rexebin/darkpurple/files/5382153/grey_orange.zip)

**Comment by rexebin** [comment] 2020-10-15 09:17
Duplicate of [https://github.com/rexebin/darcula/issues/3](url)

**Closed as completed by rexebin** 2020-10-15 09:17 UTC
